<?php

namespace Site\SavalizeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends EntityRepository
{
    
     public function adminChartFilters($startDate, $endDate, $categoryID) {
        $startDated = new \DateTime($startDate);
        $startDates = $startDated->format("Y-m-d");
        $endDate = new \DateTime($endDate);
        $endDate = $endDate->format("Y-m-d");
        // g stands for graph
        $q = $this->getEntityManager()->createQuery('
            SELECT SUM(h.price) as price , p.name as name
            FROM SiteSavalizeBundle:History h
            JOIN h.productBrand pb
            JOIN pb.product p
            WHERE p.id = pb.product
            AND p.category = :category
            AND h.baughtAt BETWEEN :start AND :end
            GROUP BY pb.product
            ')
                ->setParameter('category', $categoryID)
                ->setParameter('start', $startDates)
                ->setParameter('end', $endDate);

        $result = $q->getResult();

        return $result;
    }

    public function adminChartFiltersProductOnly($startDate, $endDate, $productID) {
        $startDated = new \DateTime($startDate);
        $startDates = $startDated->format("Y-m-d");
        $endDate = new \DateTime($endDate);
        $endDate = $endDate->format("Y-m-d");
        // g stands for graph
        $q = $this->getEntityManager()->createQuery('
            SELECT h.price as price , h.baughtAt as name
            FROM SiteSavalizeBundle:History h
            JOIN h.productBrand pb
            JOIN pb.product p
            WHERE p.id = pb.product
            AND p.id = :productID
            AND h.baughtAt BETWEEN :start AND :end
            
            ')
                ->setParameter('productID', $productID)
                ->setParameter('start', $startDates)
                ->setParameter('end', $endDate);

        $result = $q->getResult();

        return $result;
    }

    public function adminChartFiltersBrandOnly($startDate, $endDate, $brandID) {
        $startDated = new \DateTime($startDate);
        $startDates = $startDated->format("Y-m-d");
        $endDate = new \DateTime($endDate);
        $endDate = $endDate->format("Y-m-d");
        // g stands for graph
        $q = $this->getEntityManager()->createQuery('
            SELECT SUM(h.price) as price , p.name as name
            FROM SiteSavalizeBundle:History h
            JOIN h.productBrand pb
            JOIN pb.product p
            WHERE pb.brand = :brandID
            AND h.baughtAt BETWEEN :start AND :end
            GROUP BY pb.product
            ')
                ->setParameter('brandID', $brandID)
                ->setParameter('start', $startDates)
                ->setParameter('end', $endDate);

        $result = $q->getResult();

        return $result;
    }

    public function adminChartFiltersProductBrandOnly($startDate, $endDate, $brandID, $productID) {
        $startDated = new \DateTime($startDate);
        $startDates = $startDated->format("Y-m-d");
        $endDate = new \DateTime($endDate);
        $endDate = $endDate->format("Y-m-d");
        // g stands for graph
        $q = $this->getEntityManager()->createQuery('
            SELECT SUM(h.price) as price , p.name as name
            FROM SiteSavalizeBundle:History h
            JOIN h.productBrand pb
            JOIN pb.brand b
            JOIN pb.product p
            WHERE b.id = pb.brand
            AND b.id = :brandID
            AND h.baughtAt BETWEEN :start AND :end
            ')
                ->setParameter('productID', $productID)
                ->setParameter('brandID', $brandID)
                ->setParameter('start', $startDates)
                ->setParameter('end', $endDate);

        $result = $q->getResult();

        return $result;
    }
    
    public function adminChartFiltersProductBrandCategory($startDate, $endDate, $brandID, $productID, $categoryID){
        $startDated = new \DateTime($startDate);
        $startDates = $startDated->format("Y-m-d");
        $endDate = new \DateTime($endDate);
        $endDate = $endDate->format("Y-m-d");
        // g stands for graph
        $q = $this->getEntityManager()->createQuery('
            SELECT SUM(h.price) as price , h.baughtAt as name
            FROM SiteSavalizeBundle:History h
            JOIN h.productBrand pb
            JOIN pb.product p
            WHERE pb.brand = :brandID
            AND p.category = :categoryID
            AND p.id = :productID
            AND pb.product = :productID
            AND h.baughtAt BETWEEN :start AND :end
          
            ')
                ->setParameter('categoryID', $categoryID)
                ->setParameter('brandID', $brandID)
                ->setParameter('productID', $productID)
                ->setParameter('start', $startDates)
                ->setParameter('end', $endDate);

        $result = $q->getResult();

        return $result;
    }
}
