<?php

namespace Site\SavalizeBundle\Entity;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function categoryAutocomplete() {

        $q = $this->getEntityManager()->createQuery('
		SELECT c.name , c.id 
		FROM SiteSavalizeBundle:Category c 
		');
        $result = $q->getResult();
        return $result;
    }

    public function productAutocomplete($customerId) {
        $q = $this->getEntityManager()->createQuery('
		SELECT p.name , p.id 
                FROM SiteSavalizeBundle:History h
                JOIN h.productBrand pb
		JOIN pb.product p
                WHERE h.customer = :customer
                AND h.productBrand = pb.id
		')->setParameter('customer', $customerId);
        $result = $q->getResult();
     
        $result = \array_values($result);
        return $result;
    }

    public function brandAutocomplete($customerId) {

        $q = $this->getEntityManager()->createQuery('
		SELECT b.name , b.id 
		FROM SiteSavalizeBundle:History h
                JOIN h.productBrand pb
		JOIN pb.brand b
                WHERE h.customer = :customer
		')->setParameter('customer', $customerId);
        $result = $q->getResult();
    
        $result = \array_values($result);
        return $result;
    }

}
