<?php

namespace Site\SavalizeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class CategoryRepository extends EntityRepository
{
	public function categoryAutocomplete() {
		$q = $this->getEntityManager()->createQuery('
		SELECT c.name , c.id 
		FROM SiteSavalizeBundle:Category c 
		');
		$result = $q->getResult();
		return $result;
	}
        
        public function productAutocomplete() {
		$q = $this->getEntityManager()->createQuery('
		SELECT p.name , p.id 
		FROM SiteSavalizeBundle:Product p
                AND 
		');
		$result = $q->getResult();
		return $result;
	}
        
        public function brandAutocomplete() {
		$q = $this->getEntityManager()->createQuery('
		SELECT b.name , b.id 
		FROM SiteSavalizeBundle:Brand b 
		');
		$result = $q->getResult();
		return $result;
	}
}
