<?php

namespace Site\SavalizeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{

}

// $qb = $request->createQueryBuilder('C');
//     $query = $qb 
//         ->select('C.name, I.id')
//         ->innerJoin('C.items', 'I')
//         ->getQuery();

// SELECT b.name, p.name
//             FROM SiteSavalizeBundle:Brand b
//             JOIN SiteSavalizeBundle:ProductBrand pb
//             JOIN SiteSavalizeBundle:Product p
//             WHERE b.id = pb.brand
//             and p.id = pb.product
//             and b.company = :company_id











