<?php

namespace Site\SavalizeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRatingRepository extends EntityRepository
{
	public function getAllRatingsAndLikes($picName)
	{
	    $query = $this->getEntityManager()->createQuery('
		    select count(pRating.liked) as likesCount
		    from SiteSavalizeBundle:ProductRating pRating join pRating.productBrand pb where pb.picture= :picName
		    ')->setParameter('picName', $picName);
            return $query->getResult();
	}
	public function getUserLikeAndRating($productBrandId, $customerId)
	{
	    $query = $this->getEntityManager()->createQuery('
		    select pRating.liked as userLike, pRating.rating as userRating
		    from SiteSavalizeBundle:ProductRating pRating join pRating.customer as c join pRating.productBrand as pb
		    where c.id = :customerId and pb = :productBrandId
		    ')->setParameters(array('customerId'=> $customerId, 'productBrandId'=>$productBrandId));
            return $query->getResult();
	}
	public function updateLike($customerObj, $likeVal)
	{
		$query = $this->getEntityManager()->createQuery('
		    update SiteSavalizeBundle:ProductRatingpRating set pRating.liked = :likeVal where pRating.customer = :customerObj
		    ')->setParameters(array('customerObj'=> $customerObj, 'likeVal'=>$likeVal));
            return $query->getResult();
	}
}


