<?php

namespace Site\SavalizeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductBrandRepository extends EntityRepository
{
	public function displayCompanyProducts($company_id){
		$query = $this->getEntityManager()->createQuery('
			SELECT pb
			FROM SiteSavalizeBundle:ProductBrand pb
            JOIN SiteSavalizeBundle:Brand b
            WHERE b.id = pb.brand
            AND b.company = :company_id
            ')->setParameter('company_id', $company_id);
        return $query->getResult();
	}
}
